version: '3'
services:
  database:
    image: mysql:8.2.0
    ports:
      - 4545:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
  docker-api:
    build: './docker-api'
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy
    env_file: ./.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PORT: 3306
      MYSQL_HOST: ${MYSQL_HOST}
      HTTP_API_PORT: ${HTTP_API_PORT}
      HTTP_API_ADD: ${HTTP_API_ADD}
  docker-front:
    build: './docker-front'
    ports:
      - 8383:80
    depends_on:
      - docker-api
    stdin_open: true
    tty: true